# 1. Используем официальный образ Python
FROM python:3.11-slim

# 2. Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# 3. Устанавливаем переменную окружения, чтобы Python не буферизировал stdout и stderr
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# 4. Копируем файл с зависимостями и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 5. Копируем исходный код нашего приложения
COPY ./src ./src

# 6. Указываем команду для запуска приложения
CMD /bin/sh -c "sleep 10 && uvicorn src.main:app --host 0.0.0.0 --port 8000"
