FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN  pip install --upgrade pip & pip install --no-cache-dir -r requirements.txt

COPY src/ .
COPY tests/ .

EXPOSE 8000

CMD ["gunicorn", "main:app", "-k", "uvicorn.workers.UvicornWorker", "-w", "4", "-b", "0.0.0.0:8000"]