# Generated by Django 5.2.6 on 2025-12-14 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
